"""One command per stage, and `all` to run the lot.

    python -m ringfence.cli data       synthetic corpus
    python -m ringfence.cli features   tabular + causal graph features
    python -m ringfence.cli train      both ablation arms
    python -m ringfence.cli evaluate   every number in the README
    python -m ringfence.cli all

Nothing in the reports is produced anywhere else. If a figure cannot be
regenerated by this file from a clean checkout, it does not go in the pitch.
"""
from __future__ import annotations

import argparse
import json
import sys
import time

import numpy as np
import pandas as pd

from .config import REPORTS_DIR, ensure_dirs, load_config
from .io import read_table, write_table


def _log(msg: str) -> None:
    print(f"[{time.strftime('%H:%M:%S')}] {msg}", flush=True)


def cmd_data(cfg) -> None:
    from .datagen.generate import generate_corpus, summarise

    _log("generating synthetic corpus")
    out = generate_corpus(cfg)
    summary = summarise(out["payments"])
    _log("corpus written")
    print(summary.to_string(index=False))
    summary.to_csv(REPORTS_DIR / "corpus_summary.csv", index=False)


def cmd_features(cfg) -> None:
    from .features.graph_features import build_graph_features
    from .features.tabular import build_tabular_features

    payments = read_table("payments")
    _log(f"tabular features over {len(payments):,} payments")
    tabular = build_tabular_features(payments)
    write_table(tabular, "tabular_features")

    _log("causal graph features (snapshot roll-forward)")
    graph = build_graph_features(payments, cfg, verbose=True)
    write_table(graph, "graph_features")
    _log("features written")


def _matrix(cfg):
    from .model.dataset import assemble, split_frames

    payments = read_table("payments")
    tabular = read_table("tabular_features")
    graph = read_table("graph_features")
    matrix = assemble(payments, tabular, graph)
    return matrix, split_frames(matrix, cfg)


def cmd_train(cfg) -> None:
    from .model.train import save_arms, train_all

    matrix, splits = _matrix(cfg)
    for name, frame in splits.items():
        dropped = frame.attrs.get("dropped_immature", 0)
        _log(
            f"split {name:<5} rows={len(frame):>7} fraud={int(frame['is_fraud'].sum()):>6} "
            f"immature_dropped={dropped}"
        )
    _log("training ablation arms")
    arms = train_all(splits, cfg)
    save_arms(arms)
    matrix.to_pickle(REPORTS_DIR / "matrix.pkl")
    _log("models written")


def cmd_evaluate(cfg) -> None:
    from .evaluation import cost as cost_mod
    from .evaluation import metrics as met
    from .model.train import load_arms, predict

    matrix, splits = _matrix(cfg)
    arms = load_arms()
    test = splits["test"].reset_index(drop=True)
    train = splits["train"]
    y = test["is_fraud"].to_numpy().astype(int)
    amounts_inr = test["amount"].to_numpy() / 100.0
    costs = dict(cfg["costs"])

    report: dict = {"arms": {}}
    scores_by_arm = {}
    tables: dict[str, pd.DataFrame] = {}

    for name, arm in arms.items():
        scores = predict(arm, test)
        scores_by_arm[name] = scores
        head = met.headline(y, scores)
        ops = met.operating_table(y, scores)
        curve = cost_mod.cost_curve(y, scores, amounts_inr, costs)
        best = cost_mod.optimal_operating_point(curve)
        threshold = float(best["block_threshold"])

        report["arms"][name] = {
            "headline": head,
            "operating_points": ops.to_dict(orient="records"),
            "cost_optimal": {k: (float(v) if isinstance(v, (int, float, np.floating)) else v)
                             for k, v in best.to_dict().items()},
            "confusion_at_cost_optimal": met.confusion_at(y, scores, threshold),
        }
        tables[f"{name}_operating_points"] = ops
        tables[f"{name}_cost_curve"] = curve
        tables[f"{name}_per_archetype"] = met.per_archetype(test, scores, threshold)
        tables[f"{name}_novel_vs_seen"] = met.novel_vs_seen_rings(test, train, scores, threshold)
        tables[f"{name}_fp_composition"] = met.false_positive_composition(test, scores, threshold)
        tables[f"{name}_missed"] = met.missed_fraud_profile(test, scores, threshold)
        tables[f"{name}_sensitivity"] = cost_mod.sensitivity(y, scores, amounts_inr, costs)

    # The ablation: same rows, same threshold policy, one feature block apart.
    lift_rows = []
    for target in met.PRECISION_TARGETS:
        base = met.recall_at_precision(y, scores_by_arm["baseline"], target)
        graph = met.recall_at_precision(y, scores_by_arm["graph"], target)
        lift_rows.append(
            {
                "precision_target": target,
                "baseline_recall": round(base["recall"], 4),
                "graph_recall": round(graph["recall"], 4),
                "absolute_lift": round(graph["recall"] - base["recall"], 4),
                "relative_lift_%": round(
                    100 * (graph["recall"] - base["recall"]) / base["recall"], 1
                ) if base["recall"] > 0 else None,
            }
        )
    tables["ablation"] = pd.DataFrame(lift_rows)

    # Per-archetype at MATCHED precision. The cost-optimal thresholds differ
    # between arms (the graph arm runs at much higher precision), so comparing
    # per-archetype recall at each arm's own threshold is not apples to apples.
    # This table pins both arms to precision 0.90 and asks what each one catches.
    matched = []
    for name in arms:
        thr = met.recall_at_precision(y, scores_by_arm[name], 0.90)["threshold"]
        per = met.per_archetype(test, scores_by_arm[name], thr)
        per.insert(0, "arm", name)
        per["threshold"] = round(thr, 4)
        matched.append(per)
    matched_df = pd.concat(matched, ignore_index=True)
    tables["per_archetype_at_p90"] = matched_df

    ensure_dirs()
    for name, frame in tables.items():
        frame.to_csv(REPORTS_DIR / f"{name}.csv", index=False)
    with open(REPORTS_DIR / "results.json", "w", encoding="utf-8") as handle:
        json.dump(report, handle, indent=2, default=float)

    print()
    print("=" * 74)
    print("ABLATION - recall at fixed precision, held-out temporal test set")
    print("=" * 74)
    print(tables["ablation"].to_string(index=False))
    print()
    print("--- per-archetype recall, both arms pinned to precision 0.90 ---")
    pivot = matched_df.pivot(index="archetype", columns="arm", values="recall").round(4)
    pivot["lift"] = (pivot["graph"] - pivot["baseline"]).round(4)
    print(pivot.to_string())

    for name in arms:
        print()
        print(f"--- {name} : per-archetype recall at cost-optimal threshold ---")
        print(tables[f"{name}_per_archetype"].to_string(index=False))
        print(f"--- {name} : novel vs previously-seen rings ---")
        print(tables[f"{name}_novel_vs_seen"].to_string(index=False))
    print()
    print("--- headline ---")
    for name, payload in report["arms"].items():
        h = payload["headline"]
        c = payload["confusion_at_cost_optimal"]
        print(
            f"{name:<9} PR-AUC={h['pr_auc']:.4f}  ROC-AUC={h['roc_auc']:.4f}  "
            f"@cost-opt: P={c['precision']:.3f} R={c['recall']:.3f} "
            f"alerts={c['alert_rate']*100:.2f}% of traffic"
        )
    _log(f"reports written to {REPORTS_DIR}")


def cmd_verify(cfg) -> None:
    from .evaluation.verify import run_all

    _, splits = _matrix(cfg)
    _log("running leakage and honesty checks")
    results = run_all(splits, cfg)
    results.to_csv(REPORTS_DIR / "verification.csv", index=False)
    pd.set_option("display.width", 200)
    pd.set_option("display.max_colwidth", 110)
    print(results.to_string(index=False))
    if not bool(results["passed"].all()):
        raise SystemExit("verification FAILED - do not report these numbers")
    _log("all checks passed")


COMMANDS = {
    "data": cmd_data,
    "features": cmd_features,
    "train": cmd_train,
    "evaluate": cmd_evaluate,
    "verify": cmd_verify,
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="ringfence")
    parser.add_argument("command", choices=list(COMMANDS) + ["all"])
    parser.add_argument("--config", default=None)
    args = parser.parse_args(argv)

    cfg = load_config(args.config)
    ensure_dirs()
    steps = list(COMMANDS) if args.command == "all" else [args.command]
    for step in steps:
        COMMANDS[step](cfg)
    return 0


if __name__ == "__main__":
    sys.exit(main())
