"""One command per stage, and `all` to run the lot.

    python -m ringfence.cli data       synthetic corpus
    python -m ringfence.cli features   tabular + causal graph features
    python -m ringfence.cli train      both ablation arms
    python -m ringfence.cli evaluate   every number in the README
    python -m ringfence.cli all

Nothing in the reports is produced anywhere else. If a figure cannot be
regenerated by this file from a clean checkout, it does not go in the pitch.
"""
from __future__ import annotations

import argparse
import json
import sys
import time

import numpy as np
import pandas as pd

from .config import ensure_dirs, load_config, reports_dir
from .io import read_table, write_table


def _log(msg: str) -> None:
    print(f"[{time.strftime('%H:%M:%S')}] {msg}", flush=True)


def cmd_data(cfg) -> None:
    """Build the payment corpus for whichever dataset the config names.

    `kind: synthetic` runs the generator; any other kind runs an adapter that
    converts real data into the same canonical schema. The rest of the pipeline
    does not know or care which it got -- that is the point.
    """
    from .datagen.generate import summarise

    kind = cfg.get_path("dataset.kind", "synthetic")

    if kind == "synthetic":
        from .datagen.generate import generate_corpus

        _log("generating synthetic corpus")
        payments = generate_corpus(cfg)["payments"]
    elif kind == "ieee_cis":
        from .datasets import ieee_cis

        _log("loading IEEE-CIS (Vesta) transactions")
        payments = ieee_cis.load(cfg)
        write_table(payments, "payments")
        cover = ieee_cis.coverage(payments)
        cover.to_csv(reports_dir() / "ieee_link_coverage.csv", index=False)
        print()
        print("Identity link coverage (what actually exists to join on):")
        print(cover.to_string(index=False))
    else:
        raise SystemExit(f"unknown dataset kind: {kind}")

    summary = summarise(payments)
    _log("corpus written")
    print()
    print(summary.to_string(index=False))
    summary.to_csv(reports_dir() / "corpus_summary.csv", index=False)


def cmd_features(cfg) -> None:
    from .features.graph_features import build_graph_features
    from .features.tabular import build_tabular_features

    payments = read_table("payments")
    _log(f"tabular features over {len(payments):,} payments")
    tabular = build_tabular_features(payments)
    write_table(tabular, "tabular_features")

    _log("causal graph features (snapshot roll-forward)")
    graph = build_graph_features(payments, cfg, verbose=True)
    write_table(graph, "graph_features")
    _log("features written")


def _matrix(cfg):
    from .model.dataset import assemble, split_frames

    payments = read_table("payments")
    tabular = read_table("tabular_features")
    graph = read_table("graph_features")
    matrix = assemble(payments, tabular, graph)
    return matrix, split_frames(matrix, cfg)


def cmd_train(cfg) -> None:
    from .model.train import save_arms, train_all

    matrix, splits = _matrix(cfg)
    for name, frame in splits.items():
        dropped = frame.attrs.get("dropped_immature", 0)
        _log(
            f"split {name:<5} rows={len(frame):>7} fraud={int(frame['is_fraud'].sum()):>6} "
            f"immature_dropped={dropped}"
        )
    _log("training ablation arms")
    arms = train_all(splits, cfg)
    save_arms(arms)
    matrix.to_pickle(reports_dir() / "matrix.pkl")
    _log("models written")


def cmd_evaluate(cfg) -> None:
    from .evaluation import cost as cost_mod
    from .evaluation import metrics as met
    from .model.train import load_arms, predict

    matrix, splits = _matrix(cfg)
    arms = load_arms()
    test = splits["test"].reset_index(drop=True)
    train = splits["train"]
    y = test["is_fraud"].to_numpy().astype(int)
    amounts_inr = test["amount"].to_numpy() / 100.0
    costs = dict(cfg["costs"])

    report: dict = {"arms": {}}
    scores_by_arm = {}
    tables: dict[str, pd.DataFrame] = {}

    for name, arm in arms.items():
        scores = predict(arm, test)
        scores_by_arm[name] = scores
        head = met.headline(y, scores)
        ops = met.operating_table(y, scores)
        curve = cost_mod.cost_curve(y, scores, amounts_inr, costs)
        best = cost_mod.optimal_operating_point(curve)
        threshold = float(best["block_threshold"])

        report["arms"][name] = {
            "headline": head,
            "operating_points": ops.to_dict(orient="records"),
            "cost_optimal": {k: (float(v) if isinstance(v, (int, float, np.floating)) else v)
                             for k, v in best.to_dict().items()},
            "confusion_at_cost_optimal": met.confusion_at(y, scores, threshold),
        }
        tables[f"{name}_operating_points"] = ops
        tables[f"{name}_cost_curve"] = curve
        tables[f"{name}_per_archetype"] = met.per_archetype(test, scores, threshold)
        tables[f"{name}_novel_vs_seen"] = met.novel_vs_seen_rings(test, train, scores, threshold)
        tables[f"{name}_fp_composition"] = met.false_positive_composition(test, scores, threshold)
        tables[f"{name}_missed"] = met.missed_fraud_profile(test, scores, threshold)
        tables[f"{name}_sensitivity"] = cost_mod.sensitivity(y, scores, amounts_inr, costs)

    # The ablation: same rows, same threshold policy, one feature block apart.
    lift_rows = []
    for target in met.PRECISION_TARGETS:
        base = met.recall_at_precision(y, scores_by_arm["baseline"], target)
        graph = met.recall_at_precision(y, scores_by_arm["graph"], target)
        lift_rows.append(
            {
                "precision_target": target,
                "baseline_recall": round(base["recall"], 4),
                "graph_recall": round(graph["recall"], 4),
                "absolute_lift": round(graph["recall"] - base["recall"], 4),
                "relative_lift_%": round(
                    100 * (graph["recall"] - base["recall"]) / base["recall"], 1
                ) if base["recall"] > 0 else None,
            }
        )
    tables["ablation"] = pd.DataFrame(lift_rows)

    # Per-archetype at MATCHED precision. The cost-optimal thresholds differ
    # between arms (the graph arm runs at much higher precision), so comparing
    # per-archetype recall at each arm's own threshold is not apples to apples.
    # This table pins both arms to precision 0.90 and asks what each one catches.
    matched = []
    for name in arms:
        thr = met.recall_at_precision(y, scores_by_arm[name], 0.90)["threshold"]
        per = met.per_archetype(test, scores_by_arm[name], thr)
        per.insert(0, "arm", name)
        per["threshold"] = round(thr, 4)
        matched.append(per)
    matched_df = pd.concat(matched, ignore_index=True) if matched else pd.DataFrame()
    tables["per_archetype_at_p90"] = matched_df

    ensure_dirs()
    for name, frame in tables.items():
        frame.to_csv(reports_dir() / f"{name}.csv", index=False)
    with open(reports_dir() / "results.json", "w", encoding="utf-8") as handle:
        json.dump(report, handle, indent=2, default=float)

    print()
    print("=" * 74)
    print("ABLATION - recall at fixed precision, held-out temporal test set")
    print("=" * 74)
    print(tables["ablation"].to_string(index=False))
    print()
    if matched_df.empty or "archetype" not in matched_df.columns:
        # Real datasets label fraud, not ring membership. Say so rather than
        # inventing a breakdown.
        print("--- per-archetype recall: unavailable (dataset has no ring labels) ---")
    else:
        print("--- per-archetype recall, both arms pinned to precision 0.90 ---")
        pivot = matched_df.pivot(index="archetype", columns="arm", values="recall").round(4)
        pivot["lift"] = (pivot["graph"] - pivot["baseline"]).round(4)
        print(pivot.to_string())

    for name in arms:
        per = tables[f"{name}_per_archetype"]
        if not per.empty:
            print()
            print(f"--- {name} : per-archetype recall at cost-optimal threshold ---")
            print(per.to_string(index=False))
        print()
        print(f"--- {name} : novel vs previously-seen rings ---")
        print(tables[f"{name}_novel_vs_seen"].to_string(index=False))
    print()
    print("--- headline ---")
    for name, payload in report["arms"].items():
        h = payload["headline"]
        c = payload["confusion_at_cost_optimal"]
        print(
            f"{name:<9} PR-AUC={h['pr_auc']:.4f}  ROC-AUC={h['roc_auc']:.4f}  "
            f"@cost-opt: P={c['precision']:.3f} R={c['recall']:.3f} "
            f"alerts={c['alert_rate']*100:.2f}% of traffic"
        )
    _log(f"reports written to {reports_dir()}")


def cmd_explain(cfg, n_alerts: int = 12, n_false_positives: int = 4) -> None:
    """Produce analyst-readable explanations for the top alerts and, deliberately,
    for the worst false positives.

    The false positives are in the report on purpose. A risk team's first
    question about any new model is "show me what it gets wrong and why", and a
    system that can only explain its wins is not auditable.
    """
    import json as _json

    from .explain.evidence import EvidenceBuilder
    from .explain.reasons import attribute, build_reference, narrate
    from .model.train import load_arms, predict

    _, splits = _matrix(cfg)
    arms = load_arms()
    arm = arms["graph"]
    payments = read_table("payments").set_index("payment_id", drop=False)

    test = splits["test"].reset_index(drop=True)
    test["_score"] = predict(arm, test)

    _log("building the honest-population reference")
    reference = build_reference(splits["train"], arm.use_graph)

    ranked = test.sort_values("_score", ascending=False)
    # Sample per archetype rather than taking the global top N: card testing
    # saturates at 1.000 and would fill the entire report, hiding the two attack
    # types the graph actually contributes most to.
    per_type = max(1, n_alerts // 3)
    picks = [
        ranked[(ranked["is_fraud"]) & (ranked["ring_type"] == archetype)].head(per_type)
        for archetype in ("card_testing", "refund_abuse", "bust_out")
    ]
    misfires = ranked[~ranked["is_fraud"]].head(n_false_positives)
    selection = pd.concat(picks + [misfires]).reset_index(drop=True)

    _log(f"attributing {len(selection)} alerts")
    attributions = attribute(arm, selection, reference)

    builder = EvidenceBuilder(read_table("payments"), cfg)
    records, lines = [], []
    lines.append("# RingFence, alert explanations\n")
    lines.append(
        "Generated by `python -m ringfence.cli explain`. Top true-positive alerts "
        "first, then the highest-scoring **false** positives, because a model "
        "that can only explain its wins is not auditable.\n"
    )

    for _, row in selection.iterrows():
        story = narrate(
            row,
            attributions[attributions["payment_id"] == row["payment_id"]],
            reference=reference,
        )
        verdict = row["ring_type"] if row["is_fraud"] else "FALSE POSITIVE (honest account)"
        heading = f"## {row['payment_id']} , {verdict}"
        lines += [heading, "", f"**{story['summary']}**", ""]
        for reason in story["reasons"]:
            tag = "graph" if reason["from_graph"] else "transaction"
            body = "" if reason.get("generic") else f" , {reason['detail']}"
            lines.append(f"- `{reason['contribution']:+.3f}` **{reason['label']}** ({tag}){body}")
        if story.get("caveat"):
            lines.append(f"\n> {story['caveat']}")
        lines.append("")

        evidence = None
        try:
            raw_cluster = row.get("cluster")
            # NaN is truthy, so `or None` does not filter it and a missing
            # cluster was rendering as "cluster nan (0 linked accounts)".
            known = raw_cluster if isinstance(raw_cluster, str) and raw_cluster else None
            evidence = builder.evidence_for(payments.loc[row["payment_id"]], cluster=known)
        except Exception as exc:  # pragma: no cover - evidence is best-effort
            lines.append(f"_evidence unavailable: {exc}_\n")
        if evidence is not None:
            lines += ["```", evidence.render(), "```", ""]

        records.append(
            {
                **story,
                "verdict": verdict,
                "evidence": evidence.to_dict() if evidence else None,
            }
        )

    (reports_dir() / "explanations.md").write_text("\n".join(lines), encoding="utf-8")
    with open(reports_dir() / "explanations.json", "w", encoding="utf-8") as handle:
        _json.dump(records, handle, indent=2, default=str)

    graph_driven = sum(1 for r in records if r["graph_driven"])
    print()
    print(f"  {len(records)} explanations written")
    print(f"  {graph_driven}/{len(records)} were driven primarily by graph evidence")
    print()
    for record in records[:3]:
        print(f"  {record['verdict']:<28} {record['summary']}")
    _log(f"explanations written to {reports_dir() / 'explanations.md'}")


def cmd_seedstudy(cfg) -> None:
    """Refit both arms across seeds and check the gap against its noise floor."""
    from .evaluation.seed_study import run as seed_run

    matrix, splits = _matrix(cfg)
    vesta = {c for c in matrix.columns if c.startswith("src_C")}
    conditions = {"all_features": set()}
    if vesta:
        # IEEE-CIS ships Vesta's C-counters, which are literally counts of
        # addresses and phones associated with a card -- entity aggregation the
        # dataset already did. Withholding them from both arms asks whether the
        # graph earns its place when that work is not pre-done.
        conditions["without_source_entity_counters"] = vesta

    _log(f"refitting both arms across seeds ({len(conditions)} condition(s)), this is slow")
    results = seed_run(cfg, splits, conditions=conditions)
    results.to_csv(reports_dir() / "seed_study.csv", index=False)
    pd.set_option("display.width", 220)
    print()
    print(results.to_string(index=False))
    _log(f"seed study written to {reports_dir() / 'seed_study.csv'}")


def cmd_labelnoise(cfg) -> None:
    """Does the ablation gap survive training labels that are wrong?"""
    from .evaluation.label_noise import run as noise_run

    _, splits = _matrix(cfg)
    _log("retraining under corrupted training labels, this is slow")
    results = noise_run(cfg, splits)
    results.to_csv(reports_dir() / "label_noise.csv", index=False)
    pd.set_option("display.width", 220)
    print()
    print(results.to_string(index=False))
    _log(f"label-noise study written to {reports_dir() / 'label_noise.csv'}")


def cmd_structure(cfg) -> None:
    """Is there any collusion structure in this dataset to find at all?"""
    from .evaluation.structure import permutation_test

    matrix, splits = _matrix(cfg)
    test = splits["test"]
    _log("permutation test on cluster fraud concentration")
    result = permutation_test(test)

    total_fraud = int(test["is_fraud"].sum())
    sub = test[test["cluster"].fillna("").astype(str) != ""]
    per = sub.groupby("cluster")["is_fraud"].agg(["sum", "size"])
    per = per[per["size"] >= 2]
    hot = per[per["sum"] / per["size"] > 0.5]
    in_hot = int(hot["sum"].sum())
    result["fraud_in_majority_fraud_clusters"] = in_hot
    result["ceiling_share_of_all_fraud"] = round(in_hot / total_fraud, 4) if total_fraud else None

    frame = pd.DataFrame([result])
    frame.to_csv(reports_dir() / "structure_test.csv", index=False)
    print()
    for key, value in result.items():
        print(f"  {key:<36} {value}")
    print()
    print(f"  Ceiling: even if the graph caught every payment in a majority-fraud")
    print(f"  cluster and the baseline caught none, that is {in_hot}/{total_fraud} "
          f"= {100 * in_hot / max(total_fraud, 1):.2f}% of all fraud.")
    _log(f"written to {reports_dir() / 'structure_test.csv'}")


def cmd_site(cfg) -> None:
    """Bake the console into a static bundle the showcase site can serve."""
    from .api.export_static import write

    _log("baking console responses into a static bundle")
    path = write()
    size_mb = path.stat().st_size / 1e6
    _log(f"wrote {path} ({size_mb:.1f} MB)")


def cmd_serve(cfg, host: str = "127.0.0.1", port: int = 8000) -> None:
    """Run the analyst console."""
    import uvicorn

    _log(f"analyst console on http://{host}:{port} (first load builds the queue)")
    uvicorn.run("ringfence.api.service:app", host=host, port=port, log_level="warning")


def cmd_verify(cfg) -> None:
    from .evaluation.verify import run_all

    _, splits = _matrix(cfg)
    _log("running leakage and honesty checks")
    results = run_all(splits, cfg)
    results.to_csv(reports_dir() / "verification.csv", index=False)
    pd.set_option("display.width", 200)
    pd.set_option("display.max_colwidth", 110)
    print(results.to_string(index=False))
    if not bool(results["passed"].all()):
        raise SystemExit("verification FAILED - do not report these numbers")
    _log("all checks passed")


COMMANDS = {
    "data": cmd_data,
    "features": cmd_features,
    "train": cmd_train,
    "evaluate": cmd_evaluate,
    "explain": cmd_explain,
    "verify": cmd_verify,
    "seedstudy": cmd_seedstudy,
    "labelnoise": cmd_labelnoise,
    "site": cmd_site,
    "structure": cmd_structure,
    "serve": cmd_serve,
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="ringfence")
    parser.add_argument("command", choices=list(COMMANDS) + ["all"])
    parser.add_argument("--config", default=None,
                        help="config YAML (default: configs/default.yaml)")
    args = parser.parse_args(argv)

    cfg = load_config(args.config)
    ensure_dirs()
    # `all` is the reproducible pipeline; `serve` is a long-running process and
    # is never part of it.
    # `all` is the reproducible pipeline. `serve` is long-running and
    # `seedstudy` refits 20 models, so both are opt-in.
    optional = {"serve", "seedstudy", "labelnoise", "site", "structure"}
    steps = [s for s in COMMANDS if s not in optional] if args.command == "all" else [args.command]
    for step in steps:
        COMMANDS[step](cfg)
    return 0


if __name__ == "__main__":
    sys.exit(main())
